services:
  preserved-portfolio:
    container_name: web-preserved-prod-alpha
    build: .
    user: tempUser   
    networks:
      shared-network:                   
        aliases:
          - web.preserved.prod.alpha   

networks:
  shared-network:
    external: true               