services:
  preserved-portfolio:
    build: .
    container_name: preserved-portfolio
    user: tempUser   
    networks:
      - shared-network 

networks:
  shared-network:
    external: true               