/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Bazzaaaa7 (https://sketchfab.com/Bazzaaaa7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sonic-the-hedgehog-super-form-ed83cd9daf784d148c206286d237da66
Title: Sonic the Hedgehog (Super form)
*/

import React, { useRef } from 'react'
import {motion} from "framer-motion-3d";
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function SuperSonic(props) {
const group = useRef()
const { nodes, materials, animations } = useGLTF('/sonic_the_hedgehog_super_form.glb')
const { actions } = useAnimations(animations, group)
useFrame(() => {

})
return (
    <motion.group ref={group} {...props} dispose={null} position={[0.29, -0.8, 4.8]} scale={[0.9, 0.9, 0.9]} animate={{ y: [-0.8, -0.85] }} transition={{ repeat: Infinity, duration: 1.7, repeatType: "reverse", ease: "linear" }} >
    <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -2.9]}>
        <group name="e11658d242b24ddba9c0b715f449b69dfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
            <group name="RootNode">
                <group name="CameraPreset" position={[0, 0.079, 0]}>
                <group
                    name="TurnTableCamera"
                    position={[0.003, 0.478, 1.487]}
                    rotation={[3.093, 1.512, 3.14]}>
                    <group name="Object_6" />
                </group>
                </group>
                <group name="LightPreset" position={[0, 0.079, 0]}>
                <group
                    name="FillLight"
                    position={[32.178, 26.171, 0]}
                    rotation={[0.762, 0.512, -1.097]}>
                    <group name="Object_9" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_10" />
                    </group>
                </group>
                <group
                    name="BackLight"
                    position={[-12.854, 9.139, -14.74]}
                    rotation={[0.799, -0.919, 1.766]}>
                    <group name="Object_12" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_13" />
                    </group>
                </group>
                <group
                    name="KeyLight"
                    position={[-11.395, 14.365, 11.395]}
                    rotation={[0.818, -0.232, 0.573]}>
                    <group name="Object_15" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_16" />
                    </group>
                </group>
                </group>
                <group name="SuperSonic">
                <group name="Object_18">
                    <primitive object={nodes._rootJoint} />
                    <group
                    name="SuperSonic_Eyelids"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.025}
                    />
                    <group name="SuperSonic_1" rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                    <mesh
                        name="SuperSonic_Metal_0"
                        geometry={nodes.SuperSonic_Metal_0.geometry}
                        material={materials.Metal}
                    />
                    <mesh
                        name="SuperSonic_EyeL_0"
                        geometry={nodes.SuperSonic_EyeL_0.geometry}
                        material={materials.EyeL}
                    />
                    <mesh
                        name="SuperSonic_EyeR_0"
                        geometry={nodes.SuperSonic_EyeR_0.geometry}
                        material={materials.EyeR}
                    />
                    <mesh
                        name="SuperSonic_Fur_0"
                        geometry={nodes.SuperSonic_Fur_0.geometry}
                        material={materials.material}
                    />
                    <mesh
                        name="SuperSonic_Skin_0"
                        geometry={nodes.SuperSonic_Skin_0.geometry}
                        material={materials.Skin}
                    />
                    </group>
                    <group name="SuperSonic_MouthL" rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                    <mesh
                        name="SuperSonic_MouthL_Skin_0"
                        geometry={nodes.SuperSonic_MouthL_Skin_0.geometry}
                        material={materials.Skin}
                    />
                    <mesh
                        name="SuperSonic_MouthL_Metal_0"
                        geometry={nodes.SuperSonic_MouthL_Metal_0.geometry}
                        material={materials.Metal}
                    />
                    </group>
                    <group name="SuperSonic_MouthR" rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
                </group>
                </group>
            </group>
            </group>
        </group>
        </group>
    </group>
    </motion.group>
)
}

useGLTF.preload('/sonic_the_hedgehog_super_form.glb')