/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: StarWars-Universe (https://sketchfab.com/SWU)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/x-wing-6fdd3b18c4b245bf9eba1fd32611496a
Title: X-Wing
*/

import React, { useRef, useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged, useAnimations } from '@react-three/drei';
import {motion} from "framer-motion-3d";

const context = createContext()
export function InstancesX({ children, ...props }) {
const { nodes } = useGLTF('/x_wing.glb')
const instances = useMemo(
    () => ({
    XwingFuselageMainFuselageMainexterior: nodes.xwing2Fuselage_Main_Fuselage_Main_exterior_0,
    XwingFuselageMainFuseMaininterior: nodes.xwing2Fuselage_Main_Fuse_Main_interior_0,
    XwingCanopyCanopy: nodes.xwing2Canopy_Canopy_0,
    XwingCanopyGlassGlass: nodes.xwing2Canopy_Glass_Glass_0,
    XwingCockpitGlassGlass: nodes.xwing2Cockpit_Glass_Glass_0,
    XwingWingRotorAWingRotors: nodes.xwing2Wing_Rotor_A_Wing_Rotors_0,
    XwingWingRotorBWingRotors: nodes.xwing2Wing_Rotor_B_Wing_Rotors_0,
    XwingFuselageNoseFuselageNose: nodes.xwing2Fuselage_Nose_Fuselage_Nose_0,
    XwingpolymshMaterial: nodes.xwing2polymsh_Material__1811_0,
    XwingFuselageRearMaterial: nodes.xwing2Fuselage_Rear_Material__19941_0,
    XwingFuselageTopDetailMaterial: nodes.xwing2Fuselage_Top_Detail_Material__19920_0,
    XwingFuselageTopDetailMaterial1: nodes.xwing2Fuselage_Top_Detail_Material__185_0,
    XwingFuselageCockpitCockpit: nodes.xwing2Fuselage_Cockpit_Cockpit_0,
    XwingRHeadRDome: nodes.xwing2R2_Head_R2_Dome_0,
    XwingRHeadGlassy: nodes.xwing2R2_Head_Glassy_0,
    XwingRHeadRHeadmetal: nodes.xwing2R2_Head_R2_Head_metal_0,
    XwingRBodyBodymain: nodes.xwing2R2_Body_Body_main_0,
    XwingRBodyMetal: nodes.xwing2R2_Body_Metal_0,
    XwingRBodyLegs: nodes.xwing2R2_Body_Legs_0,
    XwingEngineIntakeFrontMaterial: nodes.xwing2Engine_Intake_Front_1_Material__199879_0,
    XwingEngineIntakeFrontMaterial1: nodes.xwing2Engine_Intake_Front_1_Material__19987_0,
    XwingWingInnerMaterial: nodes.xwing2Wing_Inner_1_Material__199987_0,
    XwingLasercannonMaterial: nodes.xwing2Laser_cannon_1_Material__31_0,
    XwingLasercannonMaterial1: nodes.xwing2Laser_cannon_1_Material__39_0,
    XwingLasercannonMaterial2: nodes.xwing2Laser_cannon_1_Material__34_0,
    XwingLasercannonMaterial3: nodes.xwing2Laser_cannon_1_Material__35_0,
    XwingLasercannonMaterial4: nodes.xwing2Laser_cannon_1_Material__2_0,
    XwingLasercannonMaterial5: nodes.xwing2Laser_cannon_1_Material__36_0,
    XwingLasercannonMaterial6: nodes.xwing2Laser_cannon_1_Material__32_0,
    XwingLasercannonMaterial7: nodes.xwing2Laser_cannon_1_Material__200029_0,
    XwingLasercannonMaterial8: nodes.xwing2Laser_cannon_1_Material__3_0,
    XwingEngineLowerHousingMaterial: nodes.xwing2Engine_Lower_Housing_1_Material__199915_0,
    XwingEngineLowerMaterial: nodes.xwing2Engine_Lower_1_Material__199985_0,
    XwingWingWing: nodes.xwing2Wing_1_Wing_0,
    XwingEngineIntakeUpperMaterial: nodes.xwing2Engine_Intake_Upper_1_Material__199796_0,
    XwingEngineIntakeUpperMaterial1: nodes.xwing2Engine_Intake_Upper_1_Material__19979_0,
    XwingEngineExhaustLight: nodes.xwing2Engine_Exhaust_1_Light_0,
    XwingEngineExhaustBarrel: nodes.xwing2Engine_Exhaust_1_Barrel_0,
    XwingEngineExhaustGrill: nodes.xwing2Engine_Exhaust_1_Grill_0,
    XwingEngineMainEngineMain: nodes.xwing2Engine_Main_1_Engine_Main_0,
    XwingWingBlockwingblockmat: nodes.xwing2Wing_Block_1_wing_block_mat_1_0,
    XwingEngineIntakeLowerMaterial: nodes.xwing2Engine_Intake_Lower_1_Material__199878_0,
    XwingEngineIntakeLowerMaterial1: nodes.xwing2Engine_Intake_Lower_4_Material__199878_0,
    XwingEngineLowerHousingMaterial1: nodes.xwing2Engine_Lower_Housing_4_Material__199915_0,
    XwingEngineLowerMaterial1: nodes.xwing2Engine_Lower_4_Material__199985_0,
    XwingEngineIntakeFrontMaterial2: nodes.xwing2Engine_Intake_Front_4_Material__199879_0,
    XwingEngineIntakeFrontMaterial3: nodes.xwing2Engine_Intake_Front_4_Material__19987_0,
    XwingEngineExhaustLight1: nodes.xwing2Engine_Exhaust_4_Light_0,
    XwingEngineExhaustBarrel1: nodes.xwing2Engine_Exhaust_4_Barrel_0,
    XwingEngineExhaustGrill1: nodes.xwing2Engine_Exhaust_4_Grill_0,
    XwingEngineIntakeUpperMaterial2: nodes.xwing2Engine_Intake_Upper_4_Material__199796_0,
    XwingEngineIntakeUpperMaterial3: nodes.xwing2Engine_Intake_Upper_4_Material__19979_0,
    XwingEngineMainEngineMain1: nodes.xwing2Engine_Main_4_Engine_Main_0,
    XwingWingInnerMaterial1: nodes.xwing2Wing_Inner_4_Material__199987_0,
    XwingWingWing1: nodes.xwing2Wing_4_Wing_0,
    XwingWingBlockwingblockmat1: nodes.xwing2Wing_Block_4_wing_block_mat_1_0,
    XwingLasercannonMaterial9: nodes.xwing2Laser_cannon_4_Material__31_0,
    XwingLasercannonMaterial10: nodes.xwing2Laser_cannon_4_Material__39_0,
    XwingLasercannonMaterial11: nodes.xwing2Laser_cannon_4_Material__34_0,
    XwingLasercannonMaterial12: nodes.xwing2Laser_cannon_4_Material__35_0,
    XwingLasercannonMaterial13: nodes.xwing2Laser_cannon_4_Material__2_0,
    XwingLasercannonMaterial14: nodes.xwing2Laser_cannon_4_Material__36_0,
    XwingLasercannonMaterial15: nodes.xwing2Laser_cannon_4_Material__32_0,
    XwingLasercannonMaterial16: nodes.xwing2Laser_cannon_4_Material__200029_0,
    XwingLasercannonMaterial17: nodes.xwing2Laser_cannon_4_Material__3_0,
    XwingWingBlockwingblockmat2: nodes.xwing2Wing_Block_3_wing_block_mat_2_0,
    XwingLasercannonMaterial18: nodes.xwing2Laser_cannon_2_Material__200097_0,
    XwingLasercannonMaterial19: nodes.xwing2Laser_cannon_2_Material__200091_0,
    XwingLasercannonMaterial20: nodes.xwing2Laser_cannon_2_Material__200099_0,
    XwingLasercannonMaterial21: nodes.xwing2Laser_cannon_2_Material__200092_0,
    XwingLasercannonMaterial22: nodes.xwing2Laser_cannon_2_Material__200096_0,
    XwingLasercannonMaterial23: nodes.xwing2Laser_cannon_2_Material__200095_0,
    XwingLasercannonMaterial24: nodes.xwing2Laser_cannon_2_Material__200094_0,
    XwingLasercannonMaterial25: nodes.xwing2Laser_cannon_2_Material__200093_0,
    XwingLasercannonMaterial26: nodes.xwing2Laser_cannon_2_Material__200098_0,
    XwingWingwing: nodes.xwing2Wing_2_wing_2_0,
    XwingEngineExhaustLight2: nodes.xwing2Engine_Exhaust_2_Light_0,
    XwingEngineExhaustBarrel2: nodes.xwing2Engine_Exhaust_2_Barrel_0,
    XwingEngineExhaustGrill2: nodes.xwing2Engine_Exhaust_2_Grill_0,
    XwingEngineIntakeFrontMaterial4: nodes.xwing2Engine_Intake_Front_2_Material__199879_0,
    XwingEngineIntakeFrontMaterial5: nodes.xwing2Engine_Intake_Front_2_Material__19987_0,
    XwingEngineIntakeLowerMaterial2: nodes.xwing2Engine_Intake_Lower_2_Material__199878_0,
    XwingEngineIntakeUpperMaterial4: nodes.xwing2Engine_Intake_Upper_2_Material__200101_0,
    XwingEngineIntakeUpperMaterial5: nodes.xwing2Engine_Intake_Upper_2_Material__200100_0,
    XwingEngineMainEngineMain2: nodes.xwing2Engine_Main_2_Engine_Main_0,
    XwingWingBlockwingblockmat3: nodes.xwing2Wing_Block_2_wing_block_mat_2_0,
    XwingEngineLowerHousingMaterial2: nodes.xwing2Engine_Lower_Housing_2_Material__199915_0,
    XwingEngineLowerMaterial2: nodes.xwing2Engine_Lower_2_Material__199985_0,
    XwingWingInnerMaterial2: nodes.xwing2Wing_Inner_2_Material__199987_0,
    XwingWingInnerMaterial3: nodes.xwing2Wing_Inner_3_Material__199987_0,
    XwingEngineExhaustLight3: nodes.xwing2Engine_Exhaust_3_Light_0,
    XwingEngineExhaustBarrel3: nodes.xwing2Engine_Exhaust_3_Barrel_0,
    XwingEngineExhaustGrill3: nodes.xwing2Engine_Exhaust_3_Grill_0,
    XwingLasercannonMaterial27: nodes.xwing2Laser_cannon_3_Material__200109_0,
    XwingLasercannonMaterial28: nodes.xwing2Laser_cannon_3_Material__200102_0,
    XwingLasercannonMaterial29: nodes.xwing2Laser_cannon_3_Material__200110_0,
    XwingLasercannonMaterial30: nodes.xwing2Laser_cannon_3_Material__200108_0,
    XwingLasercannonMaterial31: nodes.xwing2Laser_cannon_3_Material__200103_0,
    XwingLasercannonMaterial32: nodes.xwing2Laser_cannon_3_Material__200107_0,
    XwingLasercannonMaterial33: nodes.xwing2Laser_cannon_3_Material__200105_0,
    XwingLasercannonMaterial34: nodes.xwing2Laser_cannon_3_Material__200104_0,
    XwingLasercannonMaterial35: nodes.xwing2Laser_cannon_3_Material__200106_0,
    XwingEngineIntakeFrontMaterial6: nodes.xwing2Engine_Intake_Front_3_Material__199879_0,
    XwingEngineIntakeFrontMaterial7: nodes.xwing2Engine_Intake_Front_3_Material__19987_0,
    XwingWingWing2: nodes.xwing2Wing_3_Wing_0,
    XwingEngineIntakeLowerMaterial3: nodes.xwing2Engine_Intake_Lower_3_Material__199878_0,
    XwingEngineIntakeUpperMaterial6: nodes.xwing2Engine_Intake_Upper_3_Material__200101_0,
    XwingEngineIntakeUpperMaterial7: nodes.xwing2Engine_Intake_Upper_3_Material__200100_0,
    XwingEngineMainEngineMain3: nodes.xwing2Engine_Main_3_Engine_Main_0,
    XwingEngineLowerHousingMaterial3: nodes.xwing2Engine_Lower_Housing_3_Material__199915_0,
    XwingEngineLowerMaterial3: nodes.xwing2Engine_Lower_3_Material__199985_0,
    }),
    [nodes]
)
return (
    <Merged meshes={instances} {...props}>
    {(instances) => (<context.Provider value={instances}>{children}</context.Provider>)}
    </Merged>
)
}

export function XWing(props) {
const instances = useContext(context)
const group = useRef()
//const { actions } = useAnimations(animations, group)
return (
    <motion.group initial={{ x: -8}} animate={{x: 19}} transition={{ ease: "easeIn", duration: 9, repeat: Infinity }} ref={group} {...props} dispose={null} scale={[0.035, 0.035, 0.035 ]} position={[-4, 0, 0]} rotation={[1.2, 1.6, 0]}>
    <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="x-wingfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
            <group name="RootNode">
                <group name="xwing2xwing2" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="xwing2Fuselage_Main">
                    <instances.XwingFuselageMainFuselageMainexterior name="xwing2Fuselage_Main_Fuselage_Main_exterior_0" />
                    <instances.XwingFuselageMainFuseMaininterior name="xwing2Fuselage_Main_Fuse_Main_interior_0" />
                    <group name="xwing2Texture_Support" position={[0, -265.401, -37.74]} />
                </group>
                <group name="xwing2Canopy">
                    <instances.XwingCanopyCanopy name="xwing2Canopy_Canopy_0" />
                </group>
                <group name="xwing2Canopy_Glass">
                    <instances.XwingCanopyGlassGlass name="xwing2Canopy_Glass_Glass_0" />
                </group>
                <group name="xwing2Cockpit_Glass">
                    <instances.XwingCockpitGlassGlass name="xwing2Cockpit_Glass_Glass_0" />
                </group>
                <group name="xwing2Wing_Rotor_A">
                    <instances.XwingWingRotorAWingRotors name="xwing2Wing_Rotor_A_Wing_Rotors_0" />
                </group>
                <group name="xwing2Wing_Rotor_B">
                    <instances.XwingWingRotorBWingRotors name="xwing2Wing_Rotor_B_Wing_Rotors_0" />
                </group>
                <group name="xwing2Fuselage_Nose">
                    <instances.XwingFuselageNoseFuselageNose name="xwing2Fuselage_Nose_Fuselage_Nose_0" />
                </group>
                <group name="xwing2Fuselage_Rear_Plug">
                    <group name="xwing2polymsh" position={[0, 0, -132.546]}>
                    <instances.XwingpolymshMaterial name="xwing2polymsh_Material__1811_0" />
                    </group>
                </group>
                <group name="xwing2Fuselage_Rear">
                    <instances.XwingFuselageRearMaterial name="xwing2Fuselage_Rear_Material__19941_0" />
                </group>
                <group name="xwing2Fuselage_Top_Detail">
                    <instances.XwingFuselageTopDetailMaterial name="xwing2Fuselage_Top_Detail_Material__19920_0" />
                    <instances.XwingFuselageTopDetailMaterial1 name="xwing2Fuselage_Top_Detail_Material__185_0" />
                </group>
                <group name="xwing2Fuselage_Cockpit">
                    <instances.XwingFuselageCockpitCockpit name="xwing2Fuselage_Cockpit_Cockpit_0" />
                </group>
                <group name="xwing2R2_Head">
                    <instances.XwingRHeadRDome name="xwing2R2_Head_R2_Dome_0" />
                    <instances.XwingRHeadGlassy name="xwing2R2_Head_Glassy_0" />
                    <instances.XwingRHeadRHeadmetal name="xwing2R2_Head_R2_Head_metal_0" />
                </group>
                <group name="xwing2R2_Body">
                    <instances.XwingRBodyBodymain name="xwing2R2_Body_Body_main_0" />
                    <instances.XwingRBodyMetal name="xwing2R2_Body_Metal_0" />
                    <instances.XwingRBodyLegs name="xwing2R2_Body_Legs_0" />
                </group>
                <group name="xwing2S_Foil_1_NeutralPose" position={[0, 1407.883, 0]}>
                    <group name="xwing2S_Foil_1" rotation={[0, -0.057, 0]}>
                    <group name="xwing2Engine_Intake_Front_1" position={[0, -1407.883, 0]}>
                        <instances.XwingEngineIntakeFrontMaterial name="xwing2Engine_Intake_Front_1_Material__199879_0" />
                        <instances.XwingEngineIntakeFrontMaterial1 name="xwing2Engine_Intake_Front_1_Material__19987_0" />
                    </group>
                    <group name="xwing2Wing_Inner_1" position={[0, -1407.883, 0]}>
                        <instances.XwingWingInnerMaterial name="xwing2Wing_Inner_1_Material__199987_0" />
                    </group>
                    <group name="xwing2Laser_cannon_1" position={[0, -1407.883, 0]}>
                        <instances.XwingLasercannonMaterial name="xwing2Laser_cannon_1_Material__31_0" />
                        <instances.XwingLasercannonMaterial1 name="xwing2Laser_cannon_1_Material__39_0" />
                        <instances.XwingLasercannonMaterial2 name="xwing2Laser_cannon_1_Material__34_0" />
                        <instances.XwingLasercannonMaterial3 name="xwing2Laser_cannon_1_Material__35_0" />
                        <instances.XwingLasercannonMaterial4 name="xwing2Laser_cannon_1_Material__2_0" />
                        <instances.XwingLasercannonMaterial5 name="xwing2Laser_cannon_1_Material__36_0" />
                        <instances.XwingLasercannonMaterial6 name="xwing2Laser_cannon_1_Material__32_0" />
                        <instances.XwingLasercannonMaterial7 name="xwing2Laser_cannon_1_Material__200029_0" />
                        <instances.XwingLasercannonMaterial8 name="xwing2Laser_cannon_1_Material__3_0" />
                    </group>
                    <group name="xwing2Engine_Lower_Housing_1" position={[0, -1407.883, 0]}>
                        <instances.XwingEngineLowerHousingMaterial name="xwing2Engine_Lower_Housing_1_Material__199915_0" />
                    </group>
                    <group name="xwing2Engine_Lower_1" position={[0, -1407.883, 0]}>
                        <instances.XwingEngineLowerMaterial name="xwing2Engine_Lower_1_Material__199985_0" />
                    </group>
                    <group name="xwing2Wing_1" position={[0, -1407.883, 0]}>
                        <instances.XwingWingWing name="xwing2Wing_1_Wing_0" />
                    </group>
                    <group name="xwing2Engine_Intake_Upper_1" position={[0, -1407.883, 0]}>
                        <instances.XwingEngineIntakeUpperMaterial name="xwing2Engine_Intake_Upper_1_Material__199796_0" />
                        <instances.XwingEngineIntakeUpperMaterial1 name="xwing2Engine_Intake_Upper_1_Material__19979_0" />
                    </group>
                    <group name="xwing2Engine_Exhaust_1" position={[0, -1407.883, 0]}>
                        <instances.XwingEngineExhaustLight name="xwing2Engine_Exhaust_1_Light_0" />
                        <instances.XwingEngineExhaustBarrel name="xwing2Engine_Exhaust_1_Barrel_0" />
                        <instances.XwingEngineExhaustGrill name="xwing2Engine_Exhaust_1_Grill_0" />
                    </group>
                    <group name="xwing2Engine_Main_1" position={[0, -1407.883, 0]}>
                        <instances.XwingEngineMainEngineMain name="xwing2Engine_Main_1_Engine_Main_0" />
                    </group>
                    <group name="xwing2Wing_Block_1" position={[0, -1407.883, 0]}>
                        <instances.XwingWingBlockwingblockmat name="xwing2Wing_Block_1_wing_block_mat_1_0" />
                    </group>
                    <group name="xwing2Engine_Intake_Lower_1" position={[0, -1407.883, 0]}>
                        <instances.XwingEngineIntakeLowerMaterial name="xwing2Engine_Intake_Lower_1_Material__199878_0" />
                    </group>
                    <group
                        name="xwing2Engine_Intake_Lower_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingEngineIntakeLowerMaterial1 name="xwing2Engine_Intake_Lower_4_Material__199878_0" />
                    </group>
                    <group
                        name="xwing2Engine_Lower_Housing_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingEngineLowerHousingMaterial1 name="xwing2Engine_Lower_Housing_4_Material__199915_0" />
                    </group>
                    <group
                        name="xwing2Engine_Lower_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingEngineLowerMaterial1 name="xwing2Engine_Lower_4_Material__199985_0" />
                    </group>
                    <group
                        name="xwing2Engine_Intake_Front_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingEngineIntakeFrontMaterial2 name="xwing2Engine_Intake_Front_4_Material__199879_0" />
                        <instances.XwingEngineIntakeFrontMaterial3 name="xwing2Engine_Intake_Front_4_Material__19987_0" />
                    </group>
                    <group
                        name="xwing2Engine_Exhaust_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingEngineExhaustLight1 name="xwing2Engine_Exhaust_4_Light_0" />
                        <instances.XwingEngineExhaustBarrel1 name="xwing2Engine_Exhaust_4_Barrel_0" />
                        <instances.XwingEngineExhaustGrill1 name="xwing2Engine_Exhaust_4_Grill_0" />
                    </group>
                    <group
                        name="xwing2Engine_Intake_Upper_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingEngineIntakeUpperMaterial2 name="xwing2Engine_Intake_Upper_4_Material__199796_0" />
                        <instances.XwingEngineIntakeUpperMaterial3 name="xwing2Engine_Intake_Upper_4_Material__19979_0" />
                    </group>
                    <group
                        name="xwing2Engine_Main_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingEngineMainEngineMain1 name="xwing2Engine_Main_4_Engine_Main_0" />
                    </group>
                    <group
                        name="xwing2Wing_Inner_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingWingInnerMaterial1 name="xwing2Wing_Inner_4_Material__199987_0" />
                    </group>
                    <group
                        name="xwing2Wing_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingWingWing1 name="xwing2Wing_4_Wing_0" />
                    </group>
                    <group
                        name="xwing2Wing_Block_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingWingBlockwingblockmat1 name="xwing2Wing_Block_4_wing_block_mat_1_0" />
                    </group>
                    <group
                        name="xwing2Laser_cannon_4"
                        position={[0, -1407.883, 0]}
                        rotation={[-Math.PI, 0, Math.PI]}>
                        <instances.XwingLasercannonMaterial9 name="xwing2Laser_cannon_4_Material__31_0" />
                        <instances.XwingLasercannonMaterial10 name="xwing2Laser_cannon_4_Material__39_0" />
                        <instances.XwingLasercannonMaterial11 name="xwing2Laser_cannon_4_Material__34_0" />
                        <instances.XwingLasercannonMaterial12 name="xwing2Laser_cannon_4_Material__35_0" />
                        <instances.XwingLasercannonMaterial13 name="xwing2Laser_cannon_4_Material__2_0" />
                        <instances.XwingLasercannonMaterial14 name="xwing2Laser_cannon_4_Material__36_0" />
                        <instances.XwingLasercannonMaterial15 name="xwing2Laser_cannon_4_Material__32_0" />
                        <instances.XwingLasercannonMaterial16 name="xwing2Laser_cannon_4_Material__200029_0" />
                        <instances.XwingLasercannonMaterial17 name="xwing2Laser_cannon_4_Material__3_0" />
                    </group>
                    </group>
                </group>
                <group name="xwing2S_Foil_2_NeutralPose" position={[0, 1407.883, -0.001]}>
                    <group name="xwing2S_Foil_2" rotation={[0, 0.057, 0]}>
                    <group
                        name="xwing2Wing_Block_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0, -Math.PI]}>
                        <instances.XwingWingBlockwingblockmat2 name="xwing2Wing_Block_3_wing_block_mat_2_0" />
                    </group>
                    <group
                        name="xwing2Laser_cannon_2"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0.262, -Math.PI]}>
                        <instances.XwingLasercannonMaterial18 name="xwing2Laser_cannon_2_Material__200097_0" />
                        <instances.XwingLasercannonMaterial19 name="xwing2Laser_cannon_2_Material__200091_0" />
                        <instances.XwingLasercannonMaterial20 name="xwing2Laser_cannon_2_Material__200099_0" />
                        <instances.XwingLasercannonMaterial21 name="xwing2Laser_cannon_2_Material__200092_0" />
                        <instances.XwingLasercannonMaterial22 name="xwing2Laser_cannon_2_Material__200096_0" />
                        <instances.XwingLasercannonMaterial23 name="xwing2Laser_cannon_2_Material__200095_0" />
                        <instances.XwingLasercannonMaterial24 name="xwing2Laser_cannon_2_Material__200094_0" />
                        <instances.XwingLasercannonMaterial25 name="xwing2Laser_cannon_2_Material__200093_0" />
                        <instances.XwingLasercannonMaterial26 name="xwing2Laser_cannon_2_Material__200098_0" />
                    </group>
                    <group
                        name="xwing2Wing_2"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0.262, -Math.PI]}>
                        <instances.XwingWingwing name="xwing2Wing_2_wing_2_0" />
                    </group>
                    <group name="xwing2Engine_Exhaust_2" position={[0, -1407.883, 0.001]}>
                        <instances.XwingEngineExhaustLight2 name="xwing2Engine_Exhaust_2_Light_0" />
                        <instances.XwingEngineExhaustBarrel2 name="xwing2Engine_Exhaust_2_Barrel_0" />
                        <instances.XwingEngineExhaustGrill2 name="xwing2Engine_Exhaust_2_Grill_0" />
                    </group>
                    <group name="xwing2Engine_Intake_Front_2" position={[0, -1407.883, 0.001]}>
                        <instances.XwingEngineIntakeFrontMaterial4 name="xwing2Engine_Intake_Front_2_Material__199879_0" />
                        <instances.XwingEngineIntakeFrontMaterial5 name="xwing2Engine_Intake_Front_2_Material__19987_0" />
                    </group>
                    <group name="xwing2Engine_Intake_Lower_2" position={[0, -1407.883, 0.001]}>
                        <instances.XwingEngineIntakeLowerMaterial2 name="xwing2Engine_Intake_Lower_2_Material__199878_0" />
                    </group>
                    <group name="xwing2Engine_Intake_Upper_2" position={[0, -1407.883, 0.001]}>
                        <instances.XwingEngineIntakeUpperMaterial4 name="xwing2Engine_Intake_Upper_2_Material__200101_0" />
                        <instances.XwingEngineIntakeUpperMaterial5 name="xwing2Engine_Intake_Upper_2_Material__200100_0" />
                    </group>
                    <group name="xwing2Engine_Main_2" position={[0, -1407.883, 0.001]}>
                        <instances.XwingEngineMainEngineMain2 name="xwing2Engine_Main_2_Engine_Main_0" />
                    </group>
                    <group name="xwing2Wing_Block_2" position={[0, -1407.883, 0.001]}>
                        <instances.XwingWingBlockwingblockmat3 name="xwing2Wing_Block_2_wing_block_mat_2_0" />
                    </group>
                    <group
                        name="xwing2Engine_Lower_Housing_2"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0, 0]}
                        scale={-1}>
                        <instances.XwingEngineLowerHousingMaterial2 name="xwing2Engine_Lower_Housing_2_Material__199915_0" />
                    </group>
                    <group
                        name="xwing2Engine_Lower_2"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0, -Math.PI]}>
                        <instances.XwingEngineLowerMaterial2 name="xwing2Engine_Lower_2_Material__199985_0" />
                    </group>
                    <group
                        name="xwing2Wing_Inner_2"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0.262, -Math.PI]}>
                        <instances.XwingWingInnerMaterial2 name="xwing2Wing_Inner_2_Material__199987_0" />
                    </group>
                    <group
                        name="xwing2Wing_Inner_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[0, -0.262, 0]}>
                        <instances.XwingWingInnerMaterial3 name="xwing2Wing_Inner_3_Material__199987_0" />
                    </group>
                    <group
                        name="xwing2Engine_Exhaust_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0, -Math.PI]}>
                        <instances.XwingEngineExhaustLight3 name="xwing2Engine_Exhaust_3_Light_0" />
                        <instances.XwingEngineExhaustBarrel3 name="xwing2Engine_Exhaust_3_Barrel_0" />
                        <instances.XwingEngineExhaustGrill3 name="xwing2Engine_Exhaust_3_Grill_0" />
                    </group>
                    <group
                        name="xwing2Laser_cannon_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[0, -0.262, 0]}>
                        <instances.XwingLasercannonMaterial27 name="xwing2Laser_cannon_3_Material__200109_0" />
                        <instances.XwingLasercannonMaterial28 name="xwing2Laser_cannon_3_Material__200102_0" />
                        <instances.XwingLasercannonMaterial29 name="xwing2Laser_cannon_3_Material__200110_0" />
                        <instances.XwingLasercannonMaterial30 name="xwing2Laser_cannon_3_Material__200108_0" />
                        <instances.XwingLasercannonMaterial31 name="xwing2Laser_cannon_3_Material__200103_0" />
                        <instances.XwingLasercannonMaterial32 name="xwing2Laser_cannon_3_Material__200107_0" />
                        <instances.XwingLasercannonMaterial33 name="xwing2Laser_cannon_3_Material__200105_0" />
                        <instances.XwingLasercannonMaterial34 name="xwing2Laser_cannon_3_Material__200104_0" />
                        <instances.XwingLasercannonMaterial35 name="xwing2Laser_cannon_3_Material__200106_0" />
                    </group>
                    <group
                        name="xwing2Engine_Intake_Front_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0, -Math.PI]}>
                        <instances.XwingEngineIntakeFrontMaterial6 name="xwing2Engine_Intake_Front_3_Material__199879_0" />
                        <instances.XwingEngineIntakeFrontMaterial7 name="xwing2Engine_Intake_Front_3_Material__19987_0" />
                    </group>
                    <group
                        name="xwing2Wing_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[0, -0.262, 0]}>
                        <instances.XwingWingWing2 name="xwing2Wing_3_Wing_0" />
                    </group>
                    <group
                        name="xwing2Engine_Intake_Lower_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0, -Math.PI]}>
                        <instances.XwingEngineIntakeLowerMaterial3 name="xwing2Engine_Intake_Lower_3_Material__199878_0" />
                    </group>
                    <group
                        name="xwing2Engine_Intake_Upper_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0, -Math.PI]}>
                        <instances.XwingEngineIntakeUpperMaterial6 name="xwing2Engine_Intake_Upper_3_Material__200101_0" />
                        <instances.XwingEngineIntakeUpperMaterial7 name="xwing2Engine_Intake_Upper_3_Material__200100_0" />
                    </group>
                    <group
                        name="xwing2Engine_Main_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[Math.PI, 0, -Math.PI]}>
                        <instances.XwingEngineMainEngineMain3 name="xwing2Engine_Main_3_Engine_Main_0" />
                    </group>
                    <group
                        name="xwing2Engine_Lower_Housing_3"
                        position={[0, -1407.883, 0.001]}
                        rotation={[0, 0, Math.PI]}
                        scale={-1}>
                        <instances.XwingEngineLowerHousingMaterial3 name="xwing2Engine_Lower_Housing_3_Material__199915_0" />
                    </group>
                    <group name="xwing2Engine_Lower_3" position={[0, -1407.883, 0.001]}>
                        <instances.XwingEngineLowerMaterial3 name="xwing2Engine_Lower_3_Material__199985_0" />
                    </group>
                    </group>
                </group>
                </group>
            </group>
            </group>
        </group>
        </group>
    </group>
    </motion.group>
)
}

useGLTF.preload('/x_wing.glb')